export interface Category {
  name: string;
  imageUrl: string;
}
export const categories: Category[] = [
  { name: "AI and ML", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Marketing", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Sales", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Copywriting", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Construction", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Databases", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Cloud", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Finance", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Collaboration", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Compliance", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Agriculture", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Healthcare", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Education", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Real Estate", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Retail", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Transportation", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Travel", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Hospitality", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Manufacturing", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Automotive", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Fashion", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Entertainment", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Gaming", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Sports", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Music", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Art", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Photography", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Videography", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Design", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Development", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Engineering", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Architecture", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Legal", imageUrl: "https://via.placeholder.com/100x100" },
  { name: "Insurance", imageUrl: "https://via.placeholder.com/100x100" },
];
