const guatemalaDepartmentsNames = [
  "Guatemala",
  "Baja Verapaz",
  "Alta Verapaz",
  "El Progreso",
  "Izabal",
  "Zacapa",
  "Chiquimula",
  "Jalapa",
  "Jutiapa",
  "Santa Rosa",
  "Guanajuato",
  "Quetzaltenango",
  "San Marcos",
  "Totonicapán",
  "Quiché",
  "Sololá",
  "Suchitepéquez",
  "Retalhuleu",
  "Escuintla",
  "Sacatepéquez",
  "Chimaltenango",
  "Petén",
  "Huehuetenango",
];

const guatemalaMunicipalitiesNames = [
  "Guatemala",
  "Santa Catarina Pinula",
  "San José Pinula",
  "San José del Golfo",
  "Palencia",
  "Chinautla",
  "San Pedro Ayampuc",
  "Mixco",
  "San Pedro Sacatepéquez",
  "San Juan Sacatepéquez",
  "San Raymundo",
  "Chuarrancho",
  "Fraijanes",
  "Amatitlán",
  "Villa Nueva",
  "Villa Canales",
  "Petapa",
  "Jocotenango",
  "San Miguel Dueñas",
  "Ciudad Vieja",
  "San Antonio Aguas Calientes",
  "Santa Catarina Barahona",
  "Santa María de Jesús",
  "Santiago Sacatepéquez",
  "San Lucas Sacatepéquez",
  "Santa Lucía Milpas Altas",
  "Magdalena Milpas Altas",
];

export { guatemalaDepartmentsNames, guatemalaMunicipalitiesNames };
